version: "3"
services:
#------------------------------ MQTT
  iot-dashboard-mosquitto:
    container_name: iot-dashboard-mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - mynetwork
    volumes:
      - .docker/mosquitto/config:/mosquitto/config
      - .docker/mosquitto/data:/mosquitto/data
      - .docker/mosquitto/log:/mosquitto/log
    ports:
      - "21883:1883"
      - "29001:9001"
      
  iot-dashboard-php: 
    build: .docker/php
    container_name: "iot-dashboard-apache"
    image: iot-dashboard-apache
    volumes:
      - .docker/apache/server.pem:/etc/ssl/certs/server.pem
      - .docker/apache/server-key.pem:/etc/ssl/private/server-key.pem
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./src:/var/www/html
    
    ports:
      - 9888:80
      - 443:443
    restart: always
    networks:
      - mynetwork

  iot-dashboard-mysql:
    image: mysql:5.7.26
    container_name: "iot-dashboard-mysql"
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 9306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - mynetwork

  iot-dashboard-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "iot-dashboard-pma"
    ports:
      - 9980:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=iot-dashboard-mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


# docker exec -it -d iot-dashboard-apache /bin/bash
# docker exec iot-dashboard-apache composer install